### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by wargio** [wargio/fufluns#1]
### Android

- [ ] Check APK Signature
  - rizin can open `META-INF/CERT.RSA` and print the pkcs7 data from `pFp`
- [ ] Check Certificates and validity, bad hashes, etc..
- [ ] Detect trackers
- [x] App is debuggable [example](https://stackoverflow.com/questions/2952140/android-how-to-mark-my-app-as-debuggable)
- [ ] Exported [example](https://stackoverflow.com/questions/27458207/what-is-the-use-of-androidexported-true-in-broadcastreceiver) [issue](https://stackoverflow.com/questions/44063387/android-app-security-test-failed-saying-component-is-not-protected-an-int) - Partial
- [ ] Test all android security best practies [link](https://developer.android.com/topic/security/best-practices)

### iOS

- [x] Weak rand function
- [ ] Sandbox Behavior (like successfully use `fork()` because calls to `fork()` are disallowed on a stock iOS device).
- [x] [TrustKit](https://github.com/datatheorem/TrustKit) pinning.

**Comment by nartes** [comment]
Any way to detect this kind of [malware](https://medium.com/csis-techblog/analysis-of-joker-a-spy-premium-subscription-bot-on-googleplay-9ad24f044451)?

An example of APK trojan that seem to be available at Google Play for a while.
Idk what way does Google check published apps.

**Comment by wargio** [comment]
i guess it is possible to add r2yara and add rules regarding malwares on the bins
